- name: Install harvester and its dependencies
  hosts: harvester
  remote_user: ubuntu
  become: yes

  tasks:
  - name: add no_proxy to etc/enviroment on harvester
    lineinfile:
      dest: /etc/environment
      line: no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,harvester.novalocal,harvester
  
  - name: install pip
    become: yes
    apt:
      name: python3-pip
      state: latest
  
  - name: clone git repository to harvester
    git:
      repo: https://github.com/JethroLong/COMP90024-Proj2.git
      dest: /mnt/storage/COMP90024-Proj2

################ Remember to change src path##################
  - name: Copy hosts file to harvester
    copy:
      src: ../hosts
      dest: /mnt/storage/COMP90024-Proj2/harvester/hosts
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: install python libraries
    shell: |
      pip3 install tweepy
      pip3 install couchdb
      pip3 install nltk

  # - name: start harvester [G1]
  #   shell: python3 /mnt/storage/COMP90024Proj2/harvester/main.py stream 2 -K &

