# Install dependencies on the host

 - name: install pip
   become: yes
   apt:
     name: ['python-pip']
     state: latest
     update_cache: yes
   when: ansible_distribution -- "Ubuntu"

# upgrade pip
- name: Update pip
  become: yes
  pip: 
    name: ['pip']
    state: latest

# install openstacksdk (for interaction with openstackapi)
- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
    

