# Common vars
availability_zone: melbourne-qh2-uom

# Volume

# webserver volume
volumes_1:
  - vol_name: vol-11
    vol_size: 30

# couchdb volume
volumes_2:
  - vol_name: vol-21
    vol_size: 30

# analyser volume
volumes_3:
  - vol_name: vol-31
    vol_size: 30

# harvester volume
volumes_4:
  - vol_name: vol-41
    vol_size: 30


# Security group
security_groups:
  - name: test_ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: test_http
    description: "security group for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: test_couchdb
    description: "security group for couchdb port 5984"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: test_icmp
    description: "security group for Ping access"
    protocol: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  - name: test_web
    description: "security group for webserver port 5000"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0



# Instances
ws_instance_name: webserver
ws_instance_image: afccf48a-9426-4618-86dc-0ceb636f0169
ws_instance_key_name: team62qnn
ws_instance_flavor: uom.mse.2c9g
db_instance_name: couchdb
db_instance_image: afccf48a-9426-4618-86dc-0ceb636f0169
db_instance_key_name: team62qnn
db_instance_flavor: uom.mse.2c9g
hr_instance_name: harvester
hr_instance_image: afccf48a-9426-4618-86dc-0ceb636f0169
hr_instance_key_name: team62qnn
hr_instance_flavor: uom.mse.2c9g
ar_instance_name: analyser
ar_instance_image: afccf48a-9426-4618-86dc-0ceb636f0169
ar_instance_key_name: team62qnn
ar_instance_flavor: uom.mse.2c9g


