# Create an instance for webserver on NeCTAR
- name: Create webserver instance
  os_server:
    name: '{{ ws_instance_name }}'
    image: '{{ ws_instance_image }}'
    key_name: '{{ ws_instance_key_name }}'
    flavor: '{{ ws_instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ os_vol_1_ids }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance_ws

# - debug:
#     msg: "Instance {{ ws_instance_name }} has been created. IP address is {{ os_instance_ws.openstack.public_v4 }}"
#   when: os_instance_ws.openstack is defined

# Create an instance for CouchDB on NeCTAR
- name: Create CouchDB and Harvester instance
  os_server:
    name: '{{ db_instance_name }}'
    image: '{{ db_instance_image }}'
    key_name: '{{ db_instance_key_name }}'
    flavor: '{{ db_instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ os_vol_2_ids }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance_db

# - debug:
#     msg: "Instance {{ db_instance_name }} has been created. IP address is {{ os_instance_db.openstack.public_v4 }}"
#   when: os_instance_db.openstack is defined


# Create an instance for Harvester and analyser on NeCTAR
- name: Create Analyser instance
  os_server:
    name: '{{ hr_instance_name }}'
    image: '{{ hr_instance_image }}'
    key_name: '{{ hr_instance_key_name }}'
    flavor: '{{ hr_instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ os_vol_3_ids }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance_hr

# - debug:
#     msg: "Instance {{ hr_instance_name }} has been created. IP address is {{ os_instance_hr.openstack.public_v4 }}"
#   when: os_instance_hr.openstack is defined

- name: Set names for instances'ip address
  set_fact:
    webserverIP: '{{ os_instance_ws.openstack.public_v4 }}'
    couchdbIP: '{{ os_instance_db.openstack.public_v4 }}'
    harvesterIP: '{{ os_instance_hr.openstack.public_v4 }}'

  