# Remove any line starting with '#' in the inventory file /deployVMs/hosts
- hosts: localhost
  tasks:
  - name: remove lines with '#' from hosts
    lineinfile:
      #dest: /Users/apple/Desktop/COMP90024-Proj2/deploy/deployVMs/hosts
      dest: ../deployVMs/hosts
      regexp: '#'
      state: absent
      
